server:
  port: 2000
spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:58847/railway
    username: root
    password: zuzfmNihlkzpqLonPjXBNjUgZcgqjQlm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
