server:
  port: 2000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Employee
    username : root
    password: Passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
