server:
  port: 2000
spring:
  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:32909/railway
    username: root
    password: CvyfsHnQrtoPJlWjqRCDlwbZoRCOGkVR
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
